### ISSUE TITLE
todo. 2023-08

### ISSUE THREAD

**Issue by wdssmq** [wdssmq/blog-astro#6]
## 0.0.1丨2023-04-29
- [x] 开坑；

**Comment by wdssmq** [comment]
## 0.0.2丨2023-08-26
- [x] Tags 字段及按 Tag 列表查看；
- [x] 列表分页及排序；
    - [x] 分页依据可配置； 
    - [x] 排序及翻页条的函数封装；
- [x] 自定义配置项独立于「主题模板」之外；
- [x] 文章数据字段的约束规范从 `src\content\config.ts` 剥离；

**Comment by wdssmq** [comment]
## 0.03丨xxxx-xx-xx
- [x] RSS 输出摘要或全文；
- [x] 配置 eslint；
- [x] 分页改为 astro 自带实现；
- [x] `/page/1/` 重定向到 `/`；
- [x] 搜索；
- [x] 评论；
- [ ] VSCode 代码片段，用于快速插入 meta 数据；「[Markdown-To-Z-Blog](https://github.com/wdssmq/Markdown-To-Z-Blog/blob/main/.vscode/md2zb.code-snippets "Markdown-To-Z-Blog")」
